### PR TITLE
Fixed issue where VSTS "Collection" URI included the team project GUI…

### PR DESCRIPTION
**Pull request by DanielBMann9000**
…D, causing authentication to fail with a 404 error

### CODE REVIEW

**Comment by giuliov** [comment]
Thanks @DanielBMann9000 I will review this over the weekend

**Comment by DanielBMann9000** [comment]
@giuliov Has this been reviewed? I'd prefer not to deploy a fork for my client.

**Comment by jessehouwing** [comment]
At the moment we're working on pushing out the latest server version of the
aggregator. That's our primary goal at the moment.

Your patch looks good. I suspect that we'll work on releasing the new
webhooks version targeting the updated tfsaggregator core soon and we can
then get this working too.

To expedite the PR, I'd you're willing to help, you could update the
tfsaggregator-webhooks to use the latest aggregator-core/develop.

**Comment by giuliov** [comment]
Sorry I lost track of this
I implemented a similar change in the `develop` branch @DanielBMann9000 
would you mind to take a loot at that?

**Comment by DanielBMann9000** [comment]
@giuliov Doesn't my change preserve backwards compatibility with older versions, which your change doesn't appear to? 

I check if the `resourceContainers` element is present first, and fall back to the existing (presumably correct-for-older-versions) behavior if it isn't. If it is present, I use the value contained in there instead.

**Pull request closed without merging**
